# Generated by Django 5.0.6 on 2026-07-04 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('DEADLINE', 'Deadline'), ('INTERVIEW', 'Interview'), ('ASSESSMENT', 'Assessment'), ('REMINDER', 'Reminder'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('enabled_reminder', models.BooleanField(default=False)),
                ('minutes_before_reminder', models.PositiveIntegerField(default=60)),
                ('sent_reminder', models.BooleanField(default=False)),
                ('external_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('synced_at_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='applications.application')),
                ('interview_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='applications.interviewstage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['user', 'start_time'], name='calendar_ap_user_id_ca187e_idx')],
            },
        ),
    ]
