# Generated by Django 5.0.6 on 2026-07-02 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_url', models.URLField(blank=True, max_length=500)),
                ('job_location', models.CharField(blank=True, max_length=255)),
                ('work_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('graduate_scheme', 'Graduate Scheme')], default='graduate_scheme', max_length=20)),
                ('job_status', models.CharField(choices=[('bookmarked', 'Bookmarked'), ('not_applied', 'Not Applied'), ('applied', 'Applied'), ('online_assessment', 'Online Assessment'), ('hirevue', 'HireVue'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('accepted', 'Accepted')], default='not_applied', max_length=20)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('job_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_phase', models.CharField(choices=[('phone_screen', 'Phone Screen'), ('online_assessment', 'Online Assessment'), ('video_interview', 'Video Interview'), ('assessment_centre', 'Assessment Centre'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('final_interview', 'Final Interview'), ('offer_call', 'Offer Call'), ('other', 'Other')], max_length=30)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('link_or_location', models.CharField(blank=True, max_length=500)),
                ('interviewer', models.CharField(blank=True, max_length=255)),
                ('job_notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_stages', to='applications.application')),
            ],
            options={
                'ordering': ['order', '-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('colour', models.CharField(default='#6366F1', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='applications', to='applications.tag'),
        ),
    ]
